shell = "sh"
timeout = 300

[[repos]]
name = "dots"
url = "https://github.com/infraflakes/dots.git"
dir = "~/Projects/dots"

[[repos]]
name = "nix"
url = "https://github.com/infraflakes/nixenv.git"
dir = "~/Projects/nix"

[[repos]]
name = "svim"
url = "https://github.com/infraflakes/svim.git"
dir = "~/.config/nvim"

[[repos]]
name = "devenv"
url = "https://github.com/infraflakes/deploy.git"
dir = "~/Projects/devenv"
branch = "dev"
