shell = "sh"
timeout = 300

[project.kiru]
url = "https://github.com/infraflakes/kiru.git"
dir = "~/Projects/kiru"
branch = "dev"
direnv = true

[project.portfolio]
url = "https://github.com/infraflakes/infraflakes.github.io.git"
dir = "~/Projects/portfolio"
direnv = true

[project.deploy]
name = "deploy"
url = "https://github.com/infraflakes/deploy.git"
dir = "~/.config/kiru"
branch = "devenv"

[project.dots]
url = "https://github.com/infraflakes/dots.git"
dir = "~/dots"

[project.nix]
url = "https://github.com/infraflakes/nixenv.git"
dir = "~/nix"

[project.svim]
url = "https://github.com/infraflakes/svim.git"
dir = "~/.config/nvim"
